# =============================================================================
# CosmoSync — Production Dockerfile
#
# swisseph is an optional Node.js native addon (Swiss Ephemeris C library).
# It is listed under optionalDependencies so npm skips it gracefully on
# Windows where VS Build Tools are absent. In Docker (Linux + build tools)
# node-gyp compiles it correctly.
#
# Build chain for swisseph:
#   python3 + make + g++  →  node-gyp  →  swisseph.node  (native addon)
#
# Why node:20-slim (Debian) and not Alpine?
#   Alpine uses musl libc. Native addons compiled against glibc (default) will
#   segfault on Alpine. Debian slim avoids that mismatch while staying small.
# =============================================================================


# =============================================================================
# Stage 1 — builder
# Installs all dependencies (compiling swisseph's C source), runs
# `prisma generate`, and produces the Next.js production build.
# =============================================================================
FROM node:20-slim AS builder

# --------------------------------------------------------------------------
# C/C++ toolchain — required by node-gyp to compile swisseph
#
#   python3  Node.js gyp build scripts are Python 3
#   make     build automation (Makefile generated by gyp)
#   g++      C++ compiler; gyp invokes g++ even for C-only projects
#
# We install into this stage only; the runner stage inherits none of this.
# --------------------------------------------------------------------------
RUN apt-get update && apt-get install -y --no-install-recommends \
        python3 \
        make \
        g++ \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy manifests first so Docker cache is only busted when they change,
# not on every source file edit.
COPY package.json package-lock.json* ./
COPY prisma ./prisma/

# --------------------------------------------------------------------------
# Install dependencies
#
# This is where node-gyp runs and compiles swisseph.c → swisseph.node.
# The resulting binary ends up at:
#   node_modules/swisseph/build/Release/swisseph.node
#
# swisseph's bundled ephemeris data files (needed for planet calculations)
# are copied into node_modules/swisseph/ephe/ automatically by npm.
#
# We use `npm install` rather than `npm ci` because swisseph cannot be
# compiled on Windows (no build tools), so it cannot be in a Windows-
# generated package-lock.json yet. After the first Docker build you can
# extract the lock file and switch to `npm ci` for reproducible builds:
#   docker create --name tmp cosmo-sync && \
#   docker cp tmp:/app/package-lock.json . && \
#   docker rm tmp
# --------------------------------------------------------------------------
RUN npm install

# --------------------------------------------------------------------------
# Generate the Prisma Client and its query-engine binary for linux-musl or
# linux-debian (whichever matches this image). Must run after npm install.
# --------------------------------------------------------------------------
RUN npx prisma generate

# Copy the full source tree, then build Next.js.
COPY . .
RUN npm run build


# =============================================================================
# Stage 2 — runner
# Lean production image. No compiler, no dev tools. Receives the compiled
# node_modules (including swisseph.node) and the Next.js output from builder.
# =============================================================================
FROM node:20-slim AS runner

WORKDIR /app

ENV NODE_ENV=production

# --------------------------------------------------------------------------
# Copy compiled node_modules from builder.
#
# This transfers:
#   • swisseph.node          — compiled native binary (platform-specific)
#   • node_modules/swisseph/ephe/
#                            — bundled Swiss Ephemeris data files (.se1, .swe)
#                              These are the files the C library reads at
#                              runtime for planetary positions. Point to them
#                              from your code with:
#                                swe.set_ephe_path(
#                                  path.join(process.cwd(),
#                                    'node_modules/swisseph/ephe'))
#   • @prisma/client + query engine binary
#   • All other runtime dependencies
# --------------------------------------------------------------------------
COPY --from=builder /app/node_modules ./node_modules

# Next.js build output
COPY --from=builder /app/.next ./.next

# Static assets (images, fonts, etc.)
COPY --from=builder /app/public ./public

# Config and manifest files required by `next start`
COPY --from=builder /app/package.json    ./package.json
COPY --from=builder /app/next.config.mjs ./next.config.mjs

# Prisma schema — needed if you run `prisma migrate deploy` on start-up
COPY --from=builder /app/prisma ./prisma

# --------------------------------------------------------------------------
# If you want additional high-precision Swiss Ephemeris files (e.g. for
# outer planets beyond 3000 AD or asteroid calculations), download them
# from https://www.astro.com/ftp/swisseph/ephe/ and add a COPY step here,
# or mount a volume at runtime:
#   docker run -v /host/ephe:/app/ephe cosmo-sync
# Then call swe.set_ephe_path('/app/ephe') in your code.
# --------------------------------------------------------------------------

EXPOSE 3000

# `next start` respects the PORT environment variable.
CMD ["npm", "run", "start"]
