'use client';

import { motion } from 'framer-motion';

interface InsightCardProps {
  insight: string;
}

export function InsightCard({ insight }: InsightCardProps) {
  // Split on the final sentence ending in "?" to highlight the reflection question
  const questionMatch = insight.match(/^([\s\S]*?)(\s*[^.!?]+\?[\s]*)$/);
  const body     = questionMatch ? questionMatch[1].trim() : insight;
  const question = questionMatch ? questionMatch[2].trim() : null;

  return (
    <motion.div
      initial={{ opacity: 0, y: 12, scale: 0.98 }}
      animate={{ opacity: 1, y: 0,  scale: 1 }}
      transition={{ duration: 0.5, ease: [0.4, 0, 0.2, 1] }}
      className="rounded-2xl border border-white/15 bg-gradient-to-br from-white/6 to-white/2 p-6 space-y-4"
    >
      {/* Header */}
      <div className="flex items-center gap-2">
        <span className="text-white/40 text-lg" aria-hidden>✦</span>
        <p className="text-white/50 text-xs uppercase tracking-widest">Your Insight</p>
      </div>

      {/* Insight body */}
      <blockquote className="text-white/85 text-base leading-relaxed font-light">
        {body}
      </blockquote>

      {/* Reflection question — highlighted */}
      {question && (
        <p className="text-white/60 text-sm italic leading-relaxed border-l-2 border-white/20 pl-4">
          {question}
        </p>
      )}

      <p className="text-white/20 text-xs">
        Generated by CosmoSync · Claude AI · {new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
      </p>
    </motion.div>
  );
}
